import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/provider/layout-provider";
import { Toaster } from "@/components/ui/sonner"
import AuthProvider from "@/provider/auth-provider";
import SessionProvider from "@/provider/session-provider";
import BackToTop from "@/components/navbar-collections/back-to-top";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          < SessionProvider>
        < LayoutProvider>
        {children}
        <Toaster />
         <BackToTop />
        </LayoutProvider>
          </SessionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
